// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var path;
  path = require('path');
  module.exports = function (root, file) {
    return ('/' + path.relative(root, path.resolve(root, file))).replace(/\\/g, '/');
  };
}.call(this);
