// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var bundle, traverseDependencies;
  bundle = require('./bundle');
  traverseDependencies = require('./traverse-dependencies');
  module.exports = function (entryPoint, root, options) {
    var processed;
    if (null == root)
      root = process.cwd();
    if (null == options)
      options = {};
    processed = traverseDependencies(entryPoint, root, options);
    if (options.verbose)
      console.error('\nIncluded modules:\n  ' + Object.keys(processed).sort().join('\n  '));
    return bundle(processed, entryPoint, root, options);
  };
}.call(this);
