// Generated by CoffeeScript 2.0.0-beta3
void function () {
  var $0, cache$, CJSEverywhere, combined, escodegen, fs, Jedediah, js, optionParser, options, path, positionalArgs, root;
  fs = require('fs');
  path = require('path');
  escodegen = require('escodegen');
  Jedediah = require('jedediah');
  CJSEverywhere = require('./index');
  optionParser = new Jedediah;
  optionParser.addOption('help', false, 'display this help message');
  optionParser.addParameter('export', 'x', 'NAME', 'export the given entry module as NAME');
  optionParser.addParameter('output', 'o', 'FILE', 'output to FILE instead of stdout');
  optionParser.addParameter('root', 'r', 'DIR', 'unqualified requires are relative to DIR (default: cwdv)');
  cache$ = optionParser.parse(process.argv);
  options = cache$[0];
  positionalArgs = cache$[1];
  if (options.help) {
    $0 = process.argv[0] === 'node' ? process.argv[1] : process.argv[0];
    $0 = path.basename($0);
    console.log('\n  Usage: ' + $0 + ' OPT* path/to/entry-file.{js,coffee}\n\n' + optionParser.help() + '\n');
    process.exit(0);
  }
  if (!(positionalArgs.length === 1))
    throw new Error('wrong number of entry points given; expected 1');
  root = options.root ? path.resolve(options.root) : process.cwd();
  combined = CJSEverywhere.build(positionalArgs[0], options['export'], root);
  js = escodegen.generate(combined);
  if (options.output) {
    fs.writeFileSync(options.output, js);
  } else {
    process.stdout.write('' + js + '\n');
  }
}.call(this);
