// Generated by CoffeeScript 2.0.0-beta3
void function () {
  var cache$, CJSEverywhere, combined, escodegen, flagSpec, fs, Jedediah, js, optionParser, options, paramSpec, path, positionalArgs, root;
  fs = require('fs');
  path = require('path');
  escodegen = require('escodegen');
  Jedediah = require('jedediah');
  CJSEverywhere = require('./index');
  flagSpec = [];
  paramSpec = [
    [
      [
        'export',
        'x'
      ],
      'NAME',
      'export the given entry module as NAME'
    ],
    [
      [
        'output',
        'o'
      ],
      'FILE',
      'output to FILE instead of stdout'
    ],
    [
      [
        'root',
        'r'
      ],
      'DIR',
      'unqualified requires are relative to DIR (default: cwdv)'
    ]
  ];
  optionParser = new Jedediah(flagSpec, paramSpec);
  cache$ = optionParser.parse(process.argv);
  options = cache$[0];
  positionalArgs = cache$[1];
  if (!(positionalArgs.length === 1))
    throw new Error('wrong number of entry points given; expected 1');
  root = options.root ? path.resolve(options.root) : process.cwd();
  combined = CJSEverywhere.build(positionalArgs[0], options['export'], root);
  js = escodegen.generate(combined);
  if (options.output) {
    fs.writeFileSync(options.output, js);
  } else {
    process.stdout.write('' + js + '\n');
  }
}.call(this);
