// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var CJS_DIR, CORE_MODULES, mod, NODE_CORE_MODULES, path, resolve;
  path = require('path');
  resolve = require('resolve').sync;
  CJS_DIR = path.join(__dirname, '..');
  CORE_MODULES = {
    buffer: resolve('buffer-browserify'),
    constants: resolve('constants-browserify'),
    crypto: resolve('crypto-browserify'),
    events: resolve('events-browserify'),
    http: resolve('http-browserify'),
    punycode: resolve('punycode'),
    querystring: resolve('querystring'),
    vm: resolve('vm-browserify'),
    zlib: resolve('zlib-browserify')
  };
  NODE_CORE_MODULES = [
    '_stream_duplex',
    '_stream_passthrough',
    '_stream_readable',
    '_stream_transform',
    '_stream_writable',
    'assert',
    'console',
    'domain',
    'freelist',
    'path',
    'readline',
    'stream',
    'string_decoder',
    'sys',
    'url',
    'util'
  ];
  for (var i$ = 0, length$ = NODE_CORE_MODULES.length; i$ < length$; ++i$) {
    mod = NODE_CORE_MODULES[i$];
    CORE_MODULES[mod] = path.join(CJS_DIR, 'node', 'lib', '' + mod + '.js');
  }
  module.exports = CORE_MODULES;
}.call(this);
