// Generated by CoffeeScript 2.0.0-beta4
void function () {
  var CJS_DIR, CORE_MODULES, mod, NODE_CORE_MODULES, path;
  path = require('path');
  CJS_DIR = path.join(__dirname, '..');
  CORE_MODULES = {
    buffer: path.join(CJS_DIR, 'node_modules', 'buffer-browserify', 'index.js'),
    crypto: path.join(CJS_DIR, 'node_modules', 'crypto-browserify', 'index.js'),
    events: path.join(CJS_DIR, 'node_modules', 'events-browserify', 'events.js'),
    http: path.join(CJS_DIR, 'node_modules', 'http-browserify', 'index.js'),
    querystring: path.join(CJS_DIR, 'node_modules', 'querystring', 'index.js'),
    vm: path.join(CJS_DIR, 'node_modules', 'vm-browserify', 'index.js'),
    zlib: path.join(CJS_DIR, 'node_modules', 'zlib-browserify', 'index.js')
  };
  NODE_CORE_MODULES = [
    '_stream_duplex.js',
    '_stream_passthrough.js',
    '_stream_readable.js',
    '_stream_transform.js',
    '_stream_writable.js',
    'assert',
    'console',
    'domain',
    'freelist',
    'path',
    'punycode',
    'readline',
    'stream',
    'string_decoder',
    'sys',
    'url',
    'util'
  ];
  for (var i$ = 0, length$ = NODE_CORE_MODULES.length; i$ < length$; ++i$) {
    mod = NODE_CORE_MODULES[i$];
    CORE_MODULES[mod] = path.join(CJS_DIR, 'node', 'lib', '' + mod + '.js');
  }
  module.exports = CORE_MODULES;
}.call(this);
