// Generated by CoffeeScript 2.0.0-beta4
void function () {
  var badRequireError, bundle, CoffeeScript, CORE_DIR, esprima, estraverse, fs, isCore, path, PRELUDE, relativeResolve, resolve, resolvePath, wrapFile;
  path = require('path');
  fs = require('fs');
  resolve = require('resolve');
  esprima = require('esprima');
  estraverse = require('estraverse');
  CoffeeScript = require('coffee-script-redux');
  CORE_DIR = path.join(__dirname, '..', 'core');
  isCore = function () {
    var coreFiles;
    coreFiles = fs.readdirSync(CORE_DIR);
    coreFiles = coreFiles.filter(function (f) {
      return !fs.statSync(path.join(CORE_DIR, f)).isDirectory();
    });
    coreFiles = coreFiles.map(function (f) {
      return f.replace(/\.js$/, '');
    });
    return function (x) {
      return resolve.isCore(x) || in$(x, coreFiles);
    };
  }();
  PRELUDE = "function require(file){\n  if({}.hasOwnProperty.call(require.cache, file))\n    return require.cache[file];\n\n  var resolved = require.resolve(file);\n  if(!resolved)\n    throw new Error('Failed to resolve module ' + file);\n\n  var process = {\n    title: 'browser',\n    browser: true,\n    env: {},\n    argv: [],\n    nextTick: function(fn){ setTimeout(fn, 0); },\n    cwd: function(){ return '/'; },\n    chdir: function(){}\n  };\n  var module$ = {\n    id: file,\n    require: require,\n    filename: file,\n    exports: {},\n    loaded: false,\n    parent: null,\n    children: []\n  };\n  var dirname = file.slice(0, file.lastIndexOf('/') + 1);\n  resolved.call(module$.exports, module$, module$.exports, dirname, file, process);\n  module$.loaded = true;\n  return require.cache[file] = module$.exports;\n}\n\nrequire.modules = {};\nrequire.cache = {};\n\nrequire.resolve = function(file){\n  return {}.hasOwnProperty.call(require.modules, file) ? require.modules[file] : void 0;\n};\nrequire.define = function(file, fn){ require.modules[file] = fn; };";
  wrapFile = function (name, program) {
    var wrapper, wrapperProgram;
    wrapperProgram = esprima.parse('require.define(0, function(module, exports, __dirname, __filename, process){});');
    wrapper = wrapperProgram.body[0];
    wrapper.expression['arguments'][0] = {
      type: 'Literal',
      value: name
    };
    wrapper.expression['arguments'][1].body.body = program.body;
    return wrapper;
  };
  bundle = function (processed, entryPoint, options) {
    var ast, canonicalName, exportExpression, iife, lhsExpression, program, requireEntryPoint;
    program = esprima.parse(PRELUDE);
    for (canonicalName in processed) {
      if (!isOwn$(processed, canonicalName))
        continue;
      ast = processed[canonicalName];
      program.body.push(wrapFile(canonicalName, ast));
    }
    requireEntryPoint = {
      type: 'CallExpression',
      callee: {
        type: 'Identifier',
        name: 'require'
      },
      'arguments': [{
          type: 'Literal',
          value: entryPoint
        }]
    };
    if (null != options['export']) {
      exportExpression = esprima.parse(options['export']).body[0].expression;
      lhsExpression = exportExpression.type === 'Identifier' ? {
        type: 'MemberExpression',
        computed: false,
        object: {
          type: 'Identifier',
          name: 'global'
        },
        property: {
          type: 'Identifier',
          name: exportExpression.name
        }
      } : exportExpression;
      program.body.push({
        type: 'ExpressionStatement',
        expression: {
          type: 'AssignmentExpression',
          operator: '=',
          left: lhsExpression,
          right: requireEntryPoint
        }
      });
    } else {
      program.body.push({
        type: 'ExpressionStatement',
        expression: requireEntryPoint
      });
    }
    iife = esprima.parse('void function(global){  }.call(this, this);');
    iife.body[0].expression.argument.callee.object.body.body = program.body;
    return iife;
  };
  badRequireError = function (filename, node, msg) {
    if (null != node.loc && null != (null != node.loc ? node.loc.start : void 0))
      filename = '' + filename + ':' + node.loc.start.line + ':' + node.loc.start.column;
    throw '\n    illegal require: ' + msg + '\n      `' + require('escodegen').generate(node) + '`\n      in ' + filename + '\n  ';
  };
  resolvePath = function (extensions, root, givenPath, cwd) {
    var e;
    if (isCore(givenPath)) {
      givenPath = path.resolve(path.join(CORE_DIR, '' + givenPath + '.js'));
      if (!fs.existsSync(givenPath))
        givenPath = path.resolve(path.join(CORE_DIR, 'undefined.js'));
    }
    try {
      return resolve.sync(givenPath, {
        basedir: cwd || root,
        extensions: extensions
      });
    } catch (e$) {
      e = e$;
      try {
        return resolve.sync(path.join(root, givenPath), { extensions: extensions });
      } catch (e$1) {
        e = e$1;
        throw new Error('Cannot find module "' + givenPath + '" in "' + root + '"');
      }
    }
  };
  exports.relativeResolve = relativeResolve = function (extensions, root, givenPath, cwd) {
    var resolvedPath;
    resolvedPath = resolvePath(extensions, root, givenPath, cwd);
    if (fs.existsSync(resolvedPath)) {
      return '/' + path.relative(root, resolvedPath);
    } else {
      return resolvedPath;
    }
  };
  exports.cjsify = function (entryPoint, root, options) {
    var ast, cache$, canonicalName, ext, extensions, extname, fileContents, filename, handler, handlers, processed, source, worklist;
    if (null == root)
      root = process.cwd();
    if (null == options)
      options = {};
    entryPoint = path.resolve(entryPoint);
    if (null != options.aliases)
      options.aliases;
    else
      options.aliases = {};
    handlers = {
      '.coffee': function (coffee, canonicalName) {
        return CoffeeScript.compile(CoffeeScript.parse(coffee, { raw: true }), { bare: true });
      },
      '.json': function (json, canonicalName) {
        return esprima.parse('module.exports = ' + json, {
          loc: true,
          source: canonicalName
        });
      }
    };
    for (ext in cache$ = null != options.handlers ? options.handlers : {}) {
      if (!isOwn$(cache$, ext))
        continue;
      handler = cache$[ext];
      handlers[ext] = handler;
    }
    extensions = ['.js'].concat([].slice.call(function (accum$) {
      for (ext in handlers) {
        if (!isOwn$(handlers, ext))
          continue;
        accum$.push(ext);
      }
      return accum$;
    }.call(this, [])));
    worklist = [entryPoint];
    processed = {};
    while (worklist.length) {
      filename = worklist.pop();
      canonicalName = relativeResolve(extensions, root, filename);
      if ({}.hasOwnProperty.call(processed, canonicalName))
        continue;
      if ({}.hasOwnProperty.call(options.aliases, canonicalName))
        filename = resolvePath(extensions, root, options.aliases[canonicalName]);
      extname = path.extname(filename);
      fileContents = fs.readFileSync(filename);
      processed[canonicalName] = ast = {}.hasOwnProperty.call(handlers, extname) ? handlers[extname](fileContents, canonicalName) : esprima.parse(fileContents, {
        loc: true,
        source: canonicalName
      });
      source = path.relative(root, filename);
      if (null != ast.loc)
        ast.loc;
      else
        ast.loc = {};
      ast.loc.source = source;
      estraverse.replace(ast, {
        enter: function (node, parents) {
          var cwd;
          if (null != node.loc)
            node.loc.source = source;
          if (!(node.type === 'CallExpression' && node.callee.type === 'Identifier' && node.callee.name === 'require'))
            return;
          if (!(node['arguments'].length === 1))
            badRequireError(filename, node, 'require must be given exactly one argument');
          if (!(node['arguments'][0].type === 'Literal' && typeof node['arguments'][0].value === 'string'))
            badRequireError(filename, node, 'argument of require must be a constant string');
          cwd = path.dirname(fs.realpathSync(filename));
          if (options.verbose)
            console.error('required "' + node['arguments'][0].value + '" from "' + canonicalName + '"');
          worklist.push(resolvePath(extensions, root, node['arguments'][0].value, cwd));
          return {
            type: 'CallExpression',
            callee: node.callee,
            'arguments': [{
                type: 'Literal',
                value: relativeResolve(extensions, root, node['arguments'][0].value, cwd)
              }]
          };
        }
      });
    }
    if (options.verbose)
      console.error('\nIncluded modules:\n  ' + Object.keys(processed).sort().join('\n  '));
    return bundle(processed, relativeResolve(extensions, root, entryPoint), options);
  };
  function in$(member, list) {
    for (var i = 0, length = list.length; i < length; ++i)
      if (i in list && list[i] === member)
        return true;
    return false;
  }
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
}.call(this);
