// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var canonicalise, isCore, resolvePath;
  canonicalise = require('./canonicalise');
  isCore = require('./is-core');
  resolvePath = require('./resolve-path');
  module.exports = function (extensions, root, givenPath, cwd) {
    var resolved;
    resolved = resolvePath(extensions, root, givenPath, cwd);
    if (isCore(givenPath)) {
      return givenPath;
    } else {
      return canonicalise(root, resolved);
    }
  };
}.call(this);
