// Generated by CoffeeScript 2.0.0-beta4
void function () {
  var CORE_MODULES, fs, isCore, path, resolve;
  fs = require('fs');
  path = require('path');
  resolve = require('resolve');
  CORE_MODULES = require('./core-modules');
  isCore = require('./is-core');
  module.exports = function (extensions, root, givenPath, cwd) {
    var corePath, e;
    if (isCore(givenPath)) {
      corePath = CORE_MODULES[givenPath];
      if (!fs.existsSync(corePath))
        throw new Error('Core module "' + givenPath + '" has not yet been ported to the browser');
      givenPath = corePath;
    }
    try {
      return resolve.sync(givenPath, {
        basedir: cwd || root,
        extensions: extensions
      });
    } catch (e$) {
      e = e$;
      try {
        return resolve.sync(path.join(root, givenPath), { extensions: extensions });
      } catch (e$1) {
        e = e$1;
        throw new Error('Cannot find module "' + givenPath + '" in "' + root + '"');
      }
    }
  };
}.call(this);
